import '@/styles/globals.css';


import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata = {
  title: 'Tech Company',
  description: 'Generated by create next app'
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" suppressHydrationWarning>
      <body className="bg-[#000000]">
            <Header />
            <main>
              {/* <ThemeSwitcher /> */}
              {children}
            </main>
<Footer/>
      </body>
    </html>
  );
}
